// With-supply replay on a synthetic squeeze: logs are generated by the pool simulator itself, so the base-only shadow must
// reproduce them exactly, and adding our ladder must shrink the spike. Both pool orientations.
import { test } from "node:test";
import assert from "node:assert/strict";
import { PoolSim } from "../src/poolSim.js";
import { replayWeekend, type PoolEvent, type LadderParams } from "../src/supplyReplay.js";
import { usdToSqrtPriceX96, usdToTick } from "../src/rangeMath.js";

const D = { feed: 8, stock: 18, usd: 6 };
const SAT = 1_790_380_800;
const MON = SAT + 2 * 86_400;
const LADDER: LadderParams = {
  rungs: [ { premiumBps: 800, widthBps: 400, shareBps: 2500 }, { premiumBps: 1500, widthBps: 700, shareBps: 3000 }, { premiumBps: 2500, widthBps: 1000, shareBps: 2500 }, { premiumBps: 4000, widthBps: 1500, shareBps: 2000 } ],
  deployBps: 3000, buybackSlippageBps: 100, perfFeeBps: 1000, lockLead: 900,
};

function scenario(s0: boolean, holdingUsd: number, reopenUsd = 30.2) {
  const px = (u: number) => usdToSqrtPriceX96(BigInt(Math.round(u * 1e8)), D, s0);
  const t = (u: number) => usdToTick(BigInt(Math.round(u * 1e8)), D, s0);
  const spacing = 60;
  const [a, b] = [t(15), t(90)].sort((x, y) => x - y);
  const base = [{ tickLower: Math.ceil(a / spacing) * spacing, tickUpper: Math.floor(b / spacing) * spacing, liquidityDelta: 10n ** 17n }];
  // pick liquidity so ~$20k of buying moves the price materially: calibrate from the pool itself
  const S0 = Number(px(30)) / 2 ** 96;
  const gen = new PoolSim(S0);
  for (const m of base) gen.modify(m.tickLower, m.tickUpper, Number(m.liquidityDelta));
  gen.setPrice(S0);
  const events: PoolEvent[] = [];
  let i = 0;
  const usdIn = (usd: number, ts: number) => {
    // buyer pays USDG (token1 if stock is token0)
    const zeroForOne = !s0;
    const amt = usd * 1e6;
    gen.swap(zeroForOne, amt, 3000);
    const a0 = zeroForOne ? -BigInt(Math.round(amt)) : 1n, a1 = zeroForOne ? 1n : -BigInt(Math.round(amt));
    events.push({ kind: "swap", block: BigInt(++i), logIndex: 0, ts, amount0: a0, amount1: a1, sqrtPriceX96: BigInt(Math.round(gen.S * 2 ** 96)), liquidity: BigInt(Math.round(gen.L)), fee: 3000 });
  };
  const stockIn = (stock: number, ts: number) => {
    const zeroForOne = s0;
    const amt = stock * 1e18;
    gen.swap(zeroForOne, amt, 3000);
    const a0 = zeroForOne ? -BigInt(Math.round(amt)) : 1n, a1 = zeroForOne ? 1n : -BigInt(Math.round(amt));
    events.push({ kind: "swap", block: BigInt(++i), logIndex: 0, ts, amount0: a0, amount1: a1, sqrtPriceX96: BigInt(Math.round(gen.S * 2 ** 96)), liquidity: BigInt(Math.round(gen.L)), fee: 3000 });
  };
  const usdNow = () => (s0 ? gen.S * gen.S * 1e12 : 1e12 / (gen.S * gen.S));
  for (let k = 0; k < 250 && usdNow() < 45; k++) usdIn(2_000, SAT + 3600 + k * 300);
  let k = 0;
  while (usdNow() > reopenUsd && k < 400) stockIn(20, MON + 60 + k++);
  return replayWeekend({
    stockIs0: s0, tickSpacing: spacing, p0Usd: 30, freshUsd: reopenUsd, holdingUsd, windowStart: SAT, windowEnd: MON,
    armTime: SAT + 300, settleTime: MON + 3600, armSqrtPriceX96: px(30), baseBefore: base, events,
    settleSqrtPriceX96: BigInt(Math.round(gen.S * 2 ** 96)), gasUsd: 0,
  }, LADDER);
}

for (const s0 of [true, false]) {
  test(`with-supply shrinks the spike and still earns (stock is currency${s0 ? 0 : 1})`, () => {
    const r = scenario(s0, 10_000);
    assert.equal(r.skipped, null);
    assert.ok(r.validation.maxLogPriceErrPct < 1e-6, `shadow reproduces the logs (${r.validation.maxLogPriceErrPct})`);
    const raw = r.raw!, sup = r.supply!;
    assert.ok(raw.peakPremiumPct > 40, `raw peak ${raw.peakPremiumPct}`);
    assert.ok(sup.peakPremiumPct < raw.peakPremiumPct, `supply peak ${sup.peakPremiumPct} < raw ${raw.peakPremiumPct}`);
    assert.ok(sup.buyersPaidAboveReferenceUsd < raw.buyersPaidAboveReferenceUsd, "buyers pay less above the reference");
    assert.ok(raw.excessPct > 0 && sup.excessPct > 0, `raw ${raw.excessPct} supply ${sup.excessPct}`);
    assert.ok(sup.stockBought > 0, "buyback executed (possibly partly, capped at fresh x 1.01)");
  });
}

test("larger capital: more fills, but the spike shrinks further (capacity)", () => {
  const small = scenario(true, 1_000).supply!;
  const big = scenario(true, 100_000).supply!;
  assert.ok(big.peakPremiumPct < small.peakPremiumPct);
  assert.ok(big.usdgReceived > small.usdgReceived);
});

test("gap-up reopen above the cap leaves USDG pending, marked at the fresh price (never -100%)", () => {
  const r = scenario(true, 10_000, 44).supply!;
  assert.ok(r.usdgLeft > 0 || r.state === "OPEN");
  assert.ok(r.excessPct > -30, `bounded loss ${r.excessPct}`);
});
