// GENERATED by scripts/export-abi.mjs from keeper/src/poolSim.ts — do not edit.
// Concentrated-liquidity pool simulator for the "with our own supply" replay (docs/AIRTIGHT.md item 7).
// Rebuilds a Uniswap v4 pool from its own ModifyLiquidity history, then re-runs each historical swap's input through it,
// so our ladder's liquidity can absorb flow and shrink the spike. Floating point (sqrt price as S = sqrtPriceX96 / 2^96):
// relative error ~1e-12, far below any number we publish; the base-only replay is checked against the logged prices.
import { getSqrtPriceAtTick, MIN_TICK, MAX_TICK } from "./tickMath";

const Q96 = 2 ** 96;
const LN_TICK = Math.log(1.0001);
export const sqrtAtTick = (t: number) => Number(getSqrtPriceAtTick(t)) / Q96;
/** Largest tick whose sqrt price is <= s (float log, then corrected against exact TickMath at the boundary). */
export function tickAtSqrt(s: number): number {
  let t = Math.min(MAX_TICK - 1, Math.max(MIN_TICK, Math.floor((2 * Math.log(s)) / LN_TICK)));
  if (t === MAX_TICK - 1 || t === MIN_TICK) return t; // drained to the price bound
  if (sqrtAtTick(t + 1) <= s) t += 1;
  else if (sqrtAtTick(t) > s) t -= 1;
  return t;
}

export interface SwapResult { amountIn: number; amountOut: number; fee: number; feeToOwn: Record<string, number> }

export class PoolSim {
  /** liquidityNet per initialized tick (base LPs + ours). */
  private net = new Map<number, number>();
  private sorted: number[] | null = null;
  L = 0;
  tick: number;
  /** Our positions (keyed by id): liquidity + range. Base LPs are anonymous aggregate liquidity. */
  own = new Map<string, { L: number; lower: number; upper: number }>();

  constructor(public S: number) {
    this.tick = tickAtSqrt(S);
  }

  private ticks(): number[] {
    return (this.sorted ??= [...this.net.keys()].filter((t) => this.net.get(t) !== 0).sort((a, b) => a - b));
  }

  /** Add (dL > 0) or remove (dL < 0) liquidity on [lower, upper). */
  modify(lower: number, upper: number, dL: number) {
    if (dL === 0) return;
    this.net.set(lower, (this.net.get(lower) ?? 0) + dL);
    this.net.set(upper, (this.net.get(upper) ?? 0) - dL);
    this.sorted = null;
    if (lower <= this.tick && this.tick < upper) this.L += dL;
    if (this.L < 0 && this.L > -1e-6 * Math.abs(dL)) this.L = 0; // float dust
  }

  addOwn(id: string, lower: number, upper: number, L: number) {
    this.own.set(id, { L, lower, upper });
    this.modify(lower, upper, L);
  }
  removeOwn(id: string) {
    const p = this.own.get(id);
    if (!p) return;
    this.modify(p.lower, p.upper, -p.L);
    this.own.delete(id);
  }

  /** Active liquidity from positions containing the current tick (for validation against the logged value). */
  activeFromTicks(): number {
    let l = 0;
    for (const t of this.ticks()) if (t <= this.tick) l += this.net.get(t)!;
    return l;
  }

  /** Re-derive tick and L from a logged price (resync after drift or before a window). */
  setPrice(S: number) {
    this.S = S;
    this.tick = tickAtSqrt(S);
    this.L = Math.max(0, this.activeFromTicks());
  }

  /**
   * Exact-input swap. zeroForOne: token0 in, price (S) down. `amountIn` includes the fee (pips of 1e6).
   * `limitS` stops the swap at that price (unspent input returned as amountIn < requested).
   */
  swap(zeroForOne: boolean, amountIn: number, feePips: number, limitS?: number): SwapResult {
    // a limit already at or behind the price means no trade (v4 reverts; e.g. a capped buyback when the pool is still
    // above the cap on Monday, MSTR 29 Aug), never a trade in the opposite direction
    if (limitS !== undefined && (zeroForOne ? limitS >= this.S : limitS <= this.S)) return { amountIn: 0, amountOut: 0, fee: 0, feeToOwn: {} };
    const f = feePips / 1e6;
    let remaining = amountIn;
    let out = 0;
    let feeTotal = 0;
    const feeToOwn: Record<string, number> = {};
    const ticks = this.ticks();
    let guard = 0;
    // a rounding leftover (integer fee rounding: ~1e-7 of the input on GLXY 13 Sep) must not jump an empty range to the next liquidity (seen on GLXY 13 Sep)
    while (remaining > 1e-6 * amountIn && guard++ < 10_000) {
      // next initialized tick in the direction of travel
      let nextTick: number | undefined;
      if (zeroForOne) {
        for (let i = ticks.length - 1; i >= 0; i--) if (ticks[i] <= this.tick) { nextTick = ticks[i]; break; }
      } else {
        for (const t of ticks) if (t > this.tick) { nextTick = t; break; }
      }
      let targetS = nextTick === undefined ? (zeroForOne ? 0 : Infinity) : sqrtAtTick(nextTick);
      let hitLimit = false;
      if (limitS !== undefined && (zeroForOne ? limitS > targetS : limitS < targetS)) {
        targetS = limitS;
        hitLimit = true;
      }
      if (this.L <= 0) {
        // empty region: price jumps to the next initialized tick (no amount consumed)
        if (nextTick === undefined || hitLimit) break;
        this.cross(nextTick, zeroForOne, targetS);
        continue;
      }
      const netAvail = remaining * (1 - f);
      // net input needed to reach the target
      const need = zeroForOne ? this.L * (1 / targetS - 1 / this.S) : this.L * (targetS - this.S);
      let used: number, newS: number;
      if (Number.isFinite(need) && netAvail >= need) {
        used = need;
        newS = targetS;
      } else {
        used = netAvail;
        newS = zeroForOne ? (this.L * this.S) / (this.L + used * this.S) : this.S + used / this.L;
      }
      const gross = used / (1 - f);
      const fee = gross - used;
      const o = zeroForOne ? this.L * (this.S - newS) : this.L * (1 / this.S - 1 / newS);
      for (const [id, p] of this.own) if (p.lower <= this.tick && this.tick < p.upper) feeToOwn[id] = (feeToOwn[id] ?? 0) + (fee * p.L) / this.L;
      feeTotal += fee;
      out += o;
      remaining -= gross;
      const reached = newS === targetS;
      this.S = newS;
      if (!reached) {
        this.tick = tickAtSqrt(newS);
        break;
      }
      if (hitLimit) {
        this.tick = tickAtSqrt(newS);
        break;
      }
      if (nextTick === undefined) break;
      this.cross(nextTick, zeroForOne, targetS);
    }
    if (remaining <= 1e-6 * amountIn) remaining = 0;
    return { amountIn: amountIn - remaining, amountOut: out, fee: feeTotal, feeToOwn };
  }

  private cross(t: number, down: boolean, S: number) {
    const n = this.net.get(t) ?? 0;
    this.S = S;
    if (down) {
      this.L -= n;
      this.tick = t - 1;
    } else {
      this.L += n;
      this.tick = t;
    }
    // float dust: crossing out of the last range must leave exactly zero, or a leftover like L = 14 (seen on GLXY
    // 13 Sep) turns the next input into an infinite price move instead of stopping at the boundary like the chain
    if (this.L < 1e-6 * Math.abs(n)) this.L = 0;
  }
}

/** Token amounts of liquidity L on [sa, sb] at price S (float mirror of rangeMath.amountsForLiquidity). */
export function amountsAt(L: number, S: number, sa: number, sb: number): { amount0: number; amount1: number } {
  if (S <= sa) return { amount0: (L * (sb - sa)) / (sa * sb), amount1: 0 };
  if (S >= sb) return { amount0: 0, amount1: L * (sb - sa) };
  return { amount0: (L * (sb - S)) / (S * sb), amount1: L * (S - sa) };
}

/** Liquidity for a single-sided position of `amount` of the token that sits above/below the price. */
export function liquidityFor(amount: number, sa: number, sb: number, token0: boolean): number {
  return token0 ? (amount * sa * sb) / (sb - sa) : amount / (sb - sa);
}
