// Regenerates keeper/src/abi/*.ts from Foundry artifacts (run after `forge build`).
// CI re-runs this and fails on any diff, so the keeper can never drift from the contracts.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const targets = [["OffmintVault", "offmintVaultAbi"], ["ISessionClock", "sessionClockAbi"], ["MetaVault", "metaVaultAbi"], ["VaultFactory", "vaultFactoryAbi"]];
mkdirSync(join(root, "keeper/src/abi"), { recursive: true });
mkdirSync(join(root, "web/src/abi"), { recursive: true });
for (const [name, exportName] of targets) {
  const art = JSON.parse(readFileSync(join(root, `contracts/out/${name}.sol/${name}.json`), "utf8"));
  const body = `// GENERATED by scripts/export-abi.mjs from contracts/out/${name}.sol — do not edit.\nexport const ${exportName} = ${JSON.stringify(art.abi, null, 2)} as const;\n`;
  writeFileSync(join(root, `keeper/src/abi/${name}.ts`), body);
  writeFileSync(join(root, `web/src/abi/${name}.ts`), body); // same generated ABI for the web app
  console.log(`keeper/src/abi/${name}.ts: ${art.abi.length} entries`);
}

// Web app addresses (SPEC §9: web/src/config/addresses.<chainId>.json) from the committed deployment records.
for (const id of ["46630"]) {
  const src = join(root, `contracts/deployments/${id}.json`);
  const dst = join(root, `web/src/config/addresses.${id}.json`);
  mkdirSync(dirname(dst), { recursive: true });
  writeFileSync(dst, readFileSync(src, "utf8").trimEnd() + "\n");
  console.log(`web/src/config/addresses.${id}.json`);
}

// Range math + the replay engine for the web app (personal sell order, /sandbox simulation): the keeper's tested modules, copied so
// the web build never imports outside web/ (Railway builds web/ on its own). CI fails if the copies drift.
mkdirSync(join(root, "web/src/lib/range"), { recursive: true });
for (const name of ["tickMath", "rangeMath", "sellOrder", "poolSim", "supplyReplay"]) {
  const src = readFileSync(join(root, `keeper/src/${name}.ts`), "utf8").replace(/from "\.\/(\w+)\.js"/g, 'from "./$1"');
  writeFileSync(join(root, `web/src/lib/range/${name}.ts`), `// GENERATED by scripts/export-abi.mjs from keeper/src/${name}.ts — do not edit.\n${src}`);
  console.log(`web/src/lib/range/${name}.ts`);
}
