// Regenerates keeper/src/abi/*.ts from Foundry artifacts (run after `forge build`).
// CI re-runs this and fails on any diff, so the keeper can never drift from the contracts.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const targets = [["OffmintVault", "offmintVaultAbi"], ["ISessionClock", "sessionClockAbi"], ["MetaVault", "metaVaultAbi"], ["VaultFactory", "vaultFactoryAbi"]];
mkdirSync(join(root, "keeper/src/abi"), { recursive: true });
for (const [name, exportName] of targets) {
  const art = JSON.parse(readFileSync(join(root, `contracts/out/${name}.sol/${name}.json`), "utf8"));
  const body = `// GENERATED by scripts/export-abi.mjs from contracts/out/${name}.sol — do not edit.\nexport const ${exportName} = ${JSON.stringify(art.abi, null, 2)} as const;\n`;
  writeFileSync(join(root, `keeper/src/abi/${name}.ts`), body);
  console.log(`keeper/src/abi/${name}.ts: ${art.abi.length} entries`);
}
